import type { Metadata } from "next";
import "./globals.css";
import { DotGothic16, Silkscreen } from "next/font/google";
import localFont from 'next/font/local'

export const PixelArial = localFont({
  src: '../../public/fonts/PixelArial.ttf',
  variable: '--font-PixelArial',
  display: 'swap'
})

export const DotGothic = DotGothic16({weight: '400', variable: '--font-Dotgothic', display: 'swap'})
export const SilkscreenFont = Silkscreen({weight: '400', variable: '--font-Silkscreen', display: 'swap'})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${DotGothic.variable} ${PixelArial.variable} ${SilkscreenFont.variable} antialiased overflow-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
